dna="GAGGGGTGCGCGTGTTCGCCCAAGCTCGATACGCTGCCCCATTGGCTCTGTGGATTGCCTCGTGCGGGGTAGCACAACCTCGCCTTTGTAATGGGTATAGTTGCTATAAGCCACTGAACCCCGGCGAGGTGGAGTACTTGAGCCCGAGGTATCGTCCCTCTAGTTCTTGGGCAGTGATTTTTGGTGTCCGAAGTCGATGTAACTGTAGTTATAGATAGGTGCCTCTCAGGTCCCTTATGTAGGTACGAATGAATTGGTGCATGTATAATATCTGTTTGTGACGATCGAGGGGCCCTAGCATCAAGTCCGAATACTACAGCAACAGTTCGCGTCGCAGTGTAAACTGATATAGAAACTAGAGACGAATGATGGGCATCTTTCTGAACAGATGGTCTATATCCGCATAGTAGCACTTATTAGTCTTACGCGCAGCGCATATGGCAACGACGAAGGTGTAGGCAAAATATCACGACATTTAGATCACAGCGAGCGATTTTGATGGAAGAGCGTATGATGATGCACTGCGGGCAGAACGTAGAAGCTTCTTAACAGTTGCTGCGATGGGTTGTCGAGAGACTGGTTGATGTTACCACTACGTAAAGAACCGGCTGCTGTTAAGTCACTCCAGTGTGTGGTAGTGTGTGGGCACGTCAATCCGAGCACCTGCTTCGACTACAATGGATAACACAAAGGAGTTCAGATAGGCTCATTTCTTTACCCGGATAGGTAGAAAATATTGAAGAGTCCCGAGGAATGGCAGTATGCTGTTCTAGAACGTGTCCTACCCCTCAACGCAACCAATTACGCTCCCGAACACTCTGAA"
def counting_occurrences(word, target_letter):
    counter=0
    for letter in word:
        if letter == target_letter:
            counter+=1
        else:
            continue
    return counter

counting_occurrences(dna, "A"), counting_occurrences(dna, "C"), counting_occurrences(dna, "G"), counting_occurrences(dna, "T")